# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: "CI Workflow"

jobs:
  check:
    name: Build, Test, Coverage
    runs-on: ubuntu-latest
    steps:
 
      - name: Checkout
        uses: actions/checkout@v2
 
      - name: Use Go 1.17.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
 
      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v2

      - name: Install additional go tools
        run: |
          go get .
        shell: bash
 
      - name: Test Coverage
        run: |
          GOFLAGS=-mod=mod go test -v ./...
        shell: bash